# Change these first
owner: Matthew-Imaginary # Your GitHub organization or username, where this repository lives
repo: ictf-uptime # The name of this repository

sites:
  - name: ImaginaryCTF
    url: https://imaginaryctf.org
    icon: https://imaginaryctf.org/img/logo.png
  - name: FDownl
    url: https://fdow.nl
    icon: https://fdow.nl/img/cover.svg


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl line if you don't have a custom domain and add your repo name there
  cname: uptime.headadvertiserperson.ml
  # baseUrl: /ictf-uptime
  logoUrl: https://imaginaryctf.org/img/logo.png #https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ImaginaryCTF Uptime
  introTitle: "Hi 👋"
  introMessage: This is the uptime website for ImaginaryCTF
  navbar:
    - title: Status
      href: /
    - title: ImaginaryCTF
      href: https://imaginaryctf.org
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
